### PR TITLE
increase the number of events detected by WatcherListener

### PR DESCRIPTION
**Pull request by lxol**
-  not tested on windows yet
- no ParallelTestExecution because of https://github.com/ensime/ensime-server/issues/1337

### CODE REVIEW

**Comment by fommil** [comment]
Windows, Windows, Windows. What are we going to do with you...

**Comment by lxol** [comment]
hmm... drone didn't even make an attempt to start a test. Died with exit code 255.

**Comment by fommil** [comment]
Oh that might be a hard drive failure on chip's machine. I'm on the train, ping me in an hour and i'll blacklit the box.

**Comment by chipsenkbeil** [comment]
Yeah, I got my hard drives in last night. Machine will be back up and running tonight, but until then you have to force push to try to get the working machine. I've hit it several times when pushing to the debugger project. You would think drone would be smart enough to avoid nodes that are unresponsive.

**Comment by lxol** [comment]
tested on all 3 platforms locally, fingers crossed for CI

**Comment by fommil** [comment]
Check the ensime-server appveyor changes I made today to see the logs. Might hint about what went wrong.

**Comment by lxol** [comment]
@fommil  I updated appveyor and expected test.log in the artifacts section but it is still empty.

**Comment by lxol** [comment]
Unfortunately when we delete a watched directory the WatchKey is not being invalidated immediately. That affects the ability of the watcher to recover from the removed base. 
I tried to tune the delay. On Linux and OS X - 20 ms seems to be okay. On Windows - 500 ms for my local win vm and 1 sec appveyor. 
Currently I put the delay after each WatchService `take()` request and with hundreds of watching directories and massive update in many of them that will result in the huge compound delay especially on Windows. 
I will try to find a better way to use a delay only where it is really required.

**Comment by lxol** [comment]
@fommil do you know if it is normal that that sonatype repo has only java7-file-watcher-2.10,  3 hours after I merged the PR.  java7-file-watcher-2.11 is still the old one.

**Comment by fommil** [comment]
the drone build must have failed, maybe check and restart it?

**Comment by lxol** [comment]
both were green, I restarted anyway...

**Comment by fommil** [comment]
the badge looks red to me.

**Comment by fommil** [comment]
I've restarted. I don't think you were logged in.

**Comment by lxol** [comment]
do I look at the wrong status? 
status

**Comment by lxol** [comment]
ok, thanks!

**Pull request merged**
