### PR TITLE
add FileWatcherSpec from ensime/ensime-server

### PR DESCRIPTION
**Pull request by lxol**
Java7Watcher  is a replacement of ApachePollingFileWatcher. All 12 tests succeeded.

### CODE REVIEW

**Comment by fommil** [comment]
failing because we have harder CI compile rules

**Comment by fommil** [comment]
you might want to change the email address you've used in this commit and squash, as it isn't recognised by github.

**Comment by fommil** [comment]
a couple of small comments, but overall this is looking really great! I can do the snapshot publish so we can use it from `ensime-server` (although that should hopefully happen automatically).

**Comment by lxol** [comment]
I think it would be better if java7-file-watcher project was a snapshot of ensime-server with java7 settings. Merging and testing would be much easier.

**Comment by fommil** [comment]
hmm, that would be extremely complex from a deployment perspective. It is much easier to manage as a dependency of `ensime-server`.

**Comment by lxol** [comment]
ahh... yes you are right. I can't see the wood for the trees. I forgot that it will be runtime decision to choose the watcher, not 2 separate java6 and java7 projects...

**Comment by lxol** [comment]
6 failed tests on windows :(

**Comment by fommil** [comment]
ouch

**Comment by fommil** [comment]
I have a Windows 7 VirtualBox image you're welcome to use for testing

**Comment by lxol** [comment]
How can I use you VirtualBox? Wouldn't it be less of a  hassle  to just create a new PR  in this project and trigger AppVeyor Windows integration testing?

**Comment by fommil** [comment]
you could use it locally to run the tests under windows.

**Comment by fommil** [comment]
(but yeah, keep triggering the tests here... if you can tolerate the time delay)

**Comment by lxol** [comment]
I added this watcher as a dependency to ensime-server and also created a watcher builder class to switch between apache and java7 watchers based on `java.version`. Tested in several projects and java versions and everything worked as expected. 

https://github.com/lxol/ensime-server/commit/37d89fc0500c9fdf71cb026692b66cf085425927

**Comment by fommil** [comment]
this is fantastic, thank you!

**Pull request merged**
