### PR TITLE
triggering AppVeyor testing

### PR DESCRIPTION
**Pull request by lxol**

### CODE REVIEW

**Comment by fommil** [comment]
why are you creating a separate PR for this, aren't the windows tests being triggered in the main PR?

**Comment by lxol** [comment]
because I have no intention to merge. It is just for testing Java 7 watcher on Windows. I found several differences from the Linux watcher that make the current test incompatible.

 For example when you delete a file in Windows it sends and `Changed` and `Removed` but linux only `Removed`. 

Another one is you can't delete a parent of directory immediately after deleting the watching dir. http://stackoverflow.com/questions/6255463/java7-watchservice-access-denied-error-trying-to-delete-recursively-watched-ne

I updated the test and sometimes it was successful in the local win 7 VM but it is unstable. I am trying to find other differences now.

**Comment by fommil** [comment]
interesting. Maybe we can ignore the `Removed` messages in the test. akka testkit supports this, even temporarily. 

Windows deletion.... **uuuuughh**. Why am I not surprised...

**Comment by lxol** [comment]
with some delays between directory deletions and ignoring `Changed`, where `Removed` is expected all test are successful now. Both Win and Linux.

I will tidy up the code tomorrow.

**Comment by fommil** [comment]
:smile: close?

**Pull request closed without merging**
