### PR TITLE
minor changes for performance and testability improvement 

### PR DESCRIPTION
**Pull request by lxol**

### CODE REVIEW

**Comment by lxol** [comment]
@fommil  can we publish the project? I am ready to submit a PR for ensime-server.

**Comment by fommil** [comment]
it publishes every time we merge :wink:

**Comment by fommil** [comment]
this is what I did last time https://github.com/fommil/ensime-server/tree/java7-file-watcher

**Comment by fommil** [comment]
specifically https://github.com/fommil/ensime-server/commit/ab584e727e2fcb7135b5bcfaf991dd384026a574

**Comment by fommil** [comment]
the linux tests are pretty unstable. in ensime-server we're using the retry feature of scalatest to handle some of the noise.

**Comment by fommil** [comment]
```
[info] - should survive deletion of the watched directory *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: fishForMessage() found unexpected message BaseRemoved(file:///tmp/1458226034210-0)
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.recv$1(TestKit.scala:387)
[info]   at akka.testkit.TestKitBase$class.fishForMessage(TestKit.scala:390)
[info]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:718)
[info]   at org.ensime.indexer.FileWatcherSpec$$anonfun$12$$anonfun$apply$mcV$sp$6$$anonfun$apply$20$$anonfun$apply$21$$anonfun$apply$22.apply(FileWatchServiceSpec.scala:208)
```

**Comment by lxol** [comment]
I think the test should be refactored to expect not only the type of the Message but also the actual file/dir.


The new watcher is slightly different from the previous one. I can not use one companion Watcher as in your java7 branch. In my version I have 2 WatchService objects for jar and class selections.
https://github.com/lxol/ensime-server/commit/e4bab99c9df7a027693b3b1d13a22fa736454c61

**Comment by fommil** [comment]
sorry, just realised you didn't have write access (I thought you had access this whole time). Merge when you're happy with it.

**Comment by lxol** [comment]
finally all test passed. The watcher is unstable when the base is deleted and almost immediately recreated. I had to add delays to the tests for that. 
I will test the watcher with ensime-server in the next couple of days and submit a PR

**Pull request merged**
